services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 127.0.0.1:${POSTGRES_HOST_PORT:-5432}:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: subquerynetwork/subql-node-substrate:v4.9.0
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/kilt_indexer
    networks:
      - default
      - private-peregrine-rpc-node-net
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/kilt_indexer
      - --targetHeight=${CUTOFF_HEIGHT:-} # SUB_COMMAND needs to be set to "reindex" to have an effect
      - --db-schema=kilt_indexer
      - --workers=4
      - --batch-size=30
      - --unfinalized-blocks=false
      # - --log-level=trace # uncomment for debugging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 50

  graphql-engine:
    image: onfinality/subql-query:v2.10.0
    ports:
      - 127.0.0.1:${GRAPHQL_HOST_PORT:-3000}:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=kilt_indexer
      - --playground
      - --indexer=http://subquery-node:3000

networks:
  private-peregrine-rpc-node-net:
    external: ${PRIVATE_NODE_ENABLE:-false}
    name: ${PRIVATE_NODE_NET_NAME:-nonet}
