version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: subquerynetwork/subql-node-substrate:v3.4.2 # versions v3.4.3 and v.3.4.4 are buggy
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    networks:
      - default
      - aw-testnet-lab
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app
      - --targetHeight=${CUTOFF_HEIGHT:-} # SUB_COMMAND needs to be set to "reindex" to have an effect
      - --db-schema=app
      - --workers=4
      - --batch-size=30
      - --unfinalized-blocks=true
      #- --log-level=trace # uncomment for debugging
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://subquery-node:3000/ready"
        ]
      interval: 3s
      timeout: 5s
      retries: 50

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000

networks:
  aw-testnet-lab:
    external: true
    name: aw-testnet-lab
