import fs from "fs";

function remove(relativePath: string) {
  fs.access(relativePath, fs.constants.F_OK, (err) => {
    if (!err) {
      console.log(`deleting ${relativePath}`);
      fs.rmSync(relativePath, { recursive: true });
    } else {
      console.log(`${relativePath} was already not existing.`);
    }
  });
}

function slash() {
  console.log("deleting all files auto-generated by this SubQuery project...");
  const autoGeneratedFiles = {
    dataFolder: ".data/",
    typesFolder: "src/types/",
    distFolder: "dist/",
    projectYamlFile: "project.yaml",
  };

  for (const element of Object.values(autoGeneratedFiles)) {
    remove(element);
  }
}

// call the function:
slash();
