name: PR
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    environment: test
    env:
      RPC_ENDPOINTS: ${{ vars.RPC_ENDPOINTS }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Run tests with Subquery Node
        run: yarn subql-node test -f https://github.com/${{ github.repository }}#${{ github.head_ref }}
